### ISSUE TITLE
CreditNote Model should allow owner_invoice_id

### ISSUE THREAD

**Issue by tiagomatos** [weareswat/invoicexpress-gem#13]
Hi,
The CreditNote Model does not allow the field:
`owner_invoice_id``

outputs:
`undefined method`owner_invoice_id=' for #Invoicexpress::Models::CreditNote:0x007f98961caff8`

which should be allowed accordingly:
https://invoicexpress.com/api/credit-notes/create
`owner_invoice_id   No  The (owner) invoice associated to this credit-note.`

**Comment by igorescobar** [comment]
@tiagomatos Yep. Seems to be missing.... although seems to be relatively simply to submit a PR and fix this, right?

**Comment by tiagomatos** [comment]
Guys, please go ahead. 

I can only do it in January.

**Comment by igorescobar** [comment]
This should be closed.

**Comment by donbonifacio** [comment]
Fixed in: https://github.com/weareswat/invoicexpress-gem/pull/22
