### ISSUE TITLE
On Invoicexpress.create_invoice, mb_reference is serialized twice

### ISSUE THREAD

**Issue by jmnsf** [weareswat/invoicexpress-gem#17]
Code is `Invoicexpress.create_invoice invoice_data`.

Where `invoice_data` includes `mb_reference = true`.

Output is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<invoice>
  <date>20/02/2016</date>
  <due_date>20/02/2016</due_date>
  <retention>0</retention>
  <mb_reference>true</mb_reference>
  <client>
    (...)
  </client>
  <items type="array">
    (...)
  </items>
  <mb_reference>true</mb_reference>
</invoice>
```

So, two mb_references.

**Comment by paulosilva86** [comment]
@jmnsf Is this the xml generated before making the request to invoices/create? Are you having any errors because of the `mb_reference` duplication?

**Comment by jmnsf** [comment]
It's the XML that gets sent to the API, as recorded by [VCR](https://github.com/vcr/vcr). Don't know if this has any practical implications because the feature isn't active and a reference isn't generated. I can get back to you once I retry and generate one.

**Comment by paulosilva86** [comment]
@jmnsf OK. But if the account doesn't have any payment provider configured the `mb_reference` params will just be ignored.
